// Generated by CIRCT firtool-1.155.0
module EXU(	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  input         io_in_valid,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input  [31:0] io_in_bits_src1,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_src2,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_src3,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input         io_in_bits_wen,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input  [3:0]  io_in_bits_rd,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input  [2:0]  io_in_bits_decode_funct3,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input         io_in_bits_decode_flags_0,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_decode_flags_1,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_decode_flags_2,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_decode_flags_3,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_in_bits_npctrap_isEbreak,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  input  [31:0] io_in_bits_npctrap_code,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output        io_out_valid,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [31:0] io_out_bits_wb_res,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output        io_out_bits_wb_wen,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [3:0]  io_out_bits_wb_rd,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [31:0] io_out_bits_wdata,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output        io_out_bits_redirect_valid,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [31:0] io_out_bits_redirect_dnpc,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [2:0]  io_out_bits_decode_funct3,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output        io_out_bits_decode_flags_1,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_out_bits_decode_flags_2,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_out_bits_decode_flags_3,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
                io_out_bits_npctrap_isEbreak,	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
  output [31:0] io_out_bits_npctrap_code	// /home/yzh/projectn/npc/src/main/EXU.scala:7:14
);

  wire [63:0] _io_out_bits_wb_res_mcycle64_simmcycle_mcycle64;	// /home/yzh/projectn/npc/src/main/CSR.scala:33:29
  wire [31:0] _res_T = io_in_bits_src1 + io_in_bits_src2;	// /home/yzh/projectn/npc/src/main/EXU.scala:17:21
  SimMcycle io_out_bits_wb_res_mcycle64_simmcycle (	// /home/yzh/projectn/npc/src/main/CSR.scala:33:29
    .ren      (io_in_bits_decode_flags_3),
    .mcycle64 (_io_out_bits_wb_res_mcycle64_simmcycle_mcycle64)
  );	// /home/yzh/projectn/npc/src/main/CSR.scala:33:29
  assign io_out_valid = io_in_valid;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_wb_res =
    (io_in_bits_decode_flags_3
       ? (io_in_bits_src2[11:0] == 12'hB00
            ? _io_out_bits_wb_res_mcycle64_simmcycle_mcycle64[31:0]
            : 32'h0)
         | (io_in_bits_src2[11:0] == 12'hB80
              ? _io_out_bits_wb_res_mcycle64_simmcycle_mcycle64[63:32]
              : 32'h0) | (io_in_bits_src2[11:0] == 12'hF11 ? 32'h79737978 : 32'h0)
         | (io_in_bits_src2[11:0] == 12'hF12 ? 32'h12211D6 : 32'h0)
       : 32'h0) | (io_in_bits_decode_flags_0 ? {io_in_bits_src3[31:2], 2'h0} : 32'h0)
    | (io_in_bits_decode_flags_3 | io_in_bits_decode_flags_0 ? 32'h0 : _res_T);	// /home/yzh/projectn/npc/src/main/CSR.scala:26:28, :27:26, :33:29, :38:27, :39:27, /home/yzh/projectn/npc/src/main/EXU.scala:6:7, :17:21, :20:32, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80, :11:10, :16:{25,40}
  assign io_out_bits_wb_wen = io_in_bits_wen;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_wb_rd = io_in_bits_rd;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_wdata = io_in_bits_src3;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_redirect_valid = io_in_bits_decode_flags_0;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_redirect_dnpc = {_res_T[31:2], 2'h0};	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7, :17:21, /home/yzh/projectn/npc/src/main/utils/Utils.scala:16:{25,40}
  assign io_out_bits_decode_funct3 = io_in_bits_decode_funct3;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_decode_flags_1 = io_in_bits_decode_flags_1;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_decode_flags_2 = io_in_bits_decode_flags_2;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_decode_flags_3 = io_in_bits_decode_flags_3;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_npctrap_isEbreak = io_in_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
  assign io_out_bits_npctrap_code = io_in_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/EXU.scala:6:7
endmodule

