// Generated by CIRCT firtool-1.155.0
module IDU(	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
  input         clock,	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
                reset,	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
                io_in_valid,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  input  [31:0] io_in_bits_inst,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_in_bits_snpc,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output        io_out_valid,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output [31:0] io_out_bits_src1,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_src2,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_src3,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output        io_out_bits_wen,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output [3:0]  io_out_bits_rd,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output [2:0]  io_out_bits_decode_funct3,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output        io_out_bits_decode_flags_0,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_decode_flags_1,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_decode_flags_2,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_decode_flags_3,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
                io_out_bits_npctrap_isEbreak,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  output [31:0] io_out_bits_npctrap_code,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  input  [31:0] io_wb_res,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  input         io_wb_wen,	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
  input  [3:0]  io_wb_rd	// /home/yzh/projectn/npc/src/main/IDU.scala:7:14
);

  wire [31:0] _R_ext_R0_data;	// /home/yzh/projectn/npc/src/main/IDU.scala:50:16
  wire [31:0] _R_ext_R1_data;	// /home/yzh/projectn/npc/src/main/IDU.scala:50:16
  wire        _isAdd_T_1 = io_in_bits_inst[14:12] == 3'h0;	// /home/yzh/projectn/npc/src/main/IDU.scala:27:20, :29:51
  wire        isAdd = io_in_bits_inst[6:2] == 5'hC & _isAdd_T_1;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :29:51, :30:{24,40}
  wire        isLui = io_in_bits_inst[6:2] == 5'hD;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :31:24
  wire        isJalr = io_in_bits_inst[6:2] == 5'h19;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :32:24
  wire        isLoad = io_in_bits_inst[6:2] == 5'h0;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :33:24
  wire        isStore = io_in_bits_inst[6:2] == 5'h8;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :34:24
  wire        isCSR = io_in_bits_inst[6:2] == 5'h1C & (|(io_in_bits_inst[14:12]));	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :27:20, :35:{24,40,51}
  wire        isEbreak = io_in_bits_inst == 32'h100073;	// /home/yzh/projectn/npc/src/main/IDU.scala:36:50
  always @(posedge clock) begin	// /home/yzh/projectn/npc/src/main/IDU.scala:37:9
    if (~reset) begin	// /home/yzh/projectn/npc/src/main/IDU.scala:37:9, :38:9
      assert__chisel3_builtin:
        assert(~io_in_valid | (&(io_in_bits_inst[1:0])))
        else $error("Assertion failed at IDU.scala:37\n");	// /home/yzh/projectn/npc/src/main/IDU.scala:37:{9,10,23,30,36}
      assert__chisel3_builtin_0:
        assert(~io_in_valid | io_in_bits_inst[6:2] == 5'h4 & _isAdd_T_1 | isJalr | isAdd
               | isLui | isLoad | isStore | isCSR | isEbreak)
        else $error("Assertion failed at IDU.scala:38\n");	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :29:{24,40,51}, :30:40, :31:24, :32:24, :33:24, :34:24, :35:40, :36:50, :37:10, :38:{9,23,33,43,52,61,71,82,91}
    end
  end // always @(posedge)
  wire        io_out_bits_wen_0 = io_in_bits_inst[6:2] != 5'h8;	// /home/yzh/projectn/npc/src/main/IDU.scala:26:20, :34:24, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:44
  R_16x32 R_ext (	// /home/yzh/projectn/npc/src/main/IDU.scala:50:16
    .R0_addr (io_in_bits_inst[23:20]),	// /home/yzh/projectn/npc/src/main/IDU.scala:51:28, :57:17
    .R0_en   (1'h1),	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
    .R0_clk  (clock),
    .R0_data (_R_ext_R0_data),
    .R1_addr (isEbreak ? 4'hA : io_in_bits_inst[18:15]),	// /home/yzh/projectn/npc/src/main/IDU.scala:36:50, :56:{16,37}
    .R1_en   (1'h1),	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
    .R1_clk  (clock),
    .R1_data (_R_ext_R1_data),
    .W0_addr (io_wb_rd),
    .W0_en   (io_wb_wen & (|io_wb_rd)),	// /home/yzh/projectn/npc/src/main/IDU.scala:50:16, :52:{50,59}, :70:20
    .W0_clk  (clock),
    .W0_data (io_wb_res)
  );	// /home/yzh/projectn/npc/src/main/IDU.scala:50:16
  assign io_out_valid = io_in_valid;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7
  assign io_out_bits_src1 = isLui ? 32'h0 : _R_ext_R1_data;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :31:24, :50:16, :62:18
  assign io_out_bits_src2 =
    (isAdd ? _R_ext_R0_data : 32'h0)
    | (isStore
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:25], io_in_bits_inst[11:7]}
         : 32'h0) | (isLui ? {io_in_bits_inst[31:12], 12'h0} : 32'h0)
    | (~isAdd & io_out_bits_wen_0 & io_in_bits_inst[6:2] != 5'hD
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:20]}
         : 32'h0);	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :23:{35,40,59}, :26:20, :30:40, :31:24, :34:24, :40:26, :41:{17,22}, :42:{30,43}, :50:16, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:{10,44,60}
  assign io_out_bits_src3 = isStore ? _R_ext_R0_data : io_in_bits_snpc;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :34:24, :50:16, :68:18
  assign io_out_bits_wen = io_out_bits_wen_0;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :34:24, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:44
  assign io_out_bits_rd = io_in_bits_inst[10:7];	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :42:43, :73:16
  assign io_out_bits_decode_funct3 = io_in_bits_inst[14:12];	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :27:20
  assign io_out_bits_decode_flags_0 = isJalr;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :32:24
  assign io_out_bits_decode_flags_1 = isLoad;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :33:24
  assign io_out_bits_decode_flags_2 = isStore;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :34:24
  assign io_out_bits_decode_flags_3 = isCSR;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :35:40
  assign io_out_bits_npctrap_isEbreak = isEbreak;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :36:50
  assign io_out_bits_npctrap_code = _R_ext_R1_data;	// /home/yzh/projectn/npc/src/main/IDU.scala:6:7, :50:16
endmodule

