// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module IFU(	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
  input         clock,	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
                reset,	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
  output [31:0] io_mem_addr,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  output        io_mem_reqValid,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  input  [31:0] io_mem_rdata,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  input         io_mem_respValid,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  output        io_out_valid,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  output [31:0] io_out_bits_inst,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
                io_out_bits_snpc,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  input         io_redirect_valid,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  input  [31:0] io_redirect_dnpc,	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
  input         io_nextInst	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
);

  reg  [31:0] PC;	// /home/yzh/projectn/npc/src/main/IFU.scala:13:19
  wire [31:0] _snpc_T = PC + 32'h4;	// /home/yzh/projectn/npc/src/main/IFU.scala:13:19, :14:17
  reg         fetchInst_REG;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:49
  reg         fetchInst;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:26
  reg         state;	// /home/yzh/projectn/npc/src/main/IFU.scala:25:22
  reg  [31:0] io_out_bits_inst_r;	// /home/yzh/projectn/npc/src/main/IFU.scala:34:68
  always @(posedge clock) begin	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
    if (reset) begin	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      PC <= 32'h30000000;	// /home/yzh/projectn/npc/src/main/IFU.scala:13:19
      fetchInst_REG <= 1'h1;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:49
      fetchInst <= 1'h0;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:{26,49}
      state <= 1'h0;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:49, :25:22
    end
    else begin	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      if (io_nextInst)	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
        PC <= {io_redirect_valid ? io_redirect_dnpc[31:2] : _snpc_T[31:2], 2'h0};	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :7:14, :13:19, :14:17, :16:19, /home/yzh/projectn/npc/src/main/utils/Utils.scala:16:40
      fetchInst_REG <= 1'h0;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:49
      fetchInst <= io_nextInst | fetchInst_REG;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:{26,39,49}
      state <= ~state & fetchInst | state & ~io_mem_respValid;	// /home/yzh/projectn/npc/src/main/IFU.scala:19:{26,49}, :25:22, :28:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80
    end
    if (io_mem_respValid)	// /home/yzh/projectn/npc/src/main/IFU.scala:7:14
      io_out_bits_inst_r <= io_mem_rdata;	// /home/yzh/projectn/npc/src/main/IFU.scala:34:68
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      automatic logic [31:0] _RANDOM[0:2];	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
        `INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
        for (logic [1:0] i = 2'h0; i < 2'h3; i += 2'h1) begin
          _RANDOM[i] = `RANDOM;	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
        end	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
        PC = _RANDOM[2'h0];	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :13:19
        fetchInst_REG = _RANDOM[2'h1][0];	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :19:49
        fetchInst = _RANDOM[2'h1][1];	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :19:{26,49}
        state = _RANDOM[2'h1][2];	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :19:49, :25:22
        io_out_bits_inst_r = {_RANDOM[2'h1][31:3], _RANDOM[2'h2][2:0]};	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :19:49, :34:68
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
      `FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_mem_addr = {PC[31:2], 2'h0};	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :13:19, /home/yzh/projectn/npc/src/main/utils/Utils.scala:16:{25,40}
  assign io_mem_reqValid = fetchInst & ~state;	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :19:26, :25:22, :31:32, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92
  assign io_out_valid = io_mem_respValid;	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7
  assign io_out_bits_inst = io_mem_respValid ? io_mem_rdata : io_out_bits_inst_r;	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :34:{26,68}
  assign io_out_bits_snpc = _snpc_T;	// /home/yzh/projectn/npc/src/main/IFU.scala:6:7, :14:17
endmodule

