// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module LSU(	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  input         clock,	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
                reset,	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
                io_in_valid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [31:0] io_in_bits_wb_res,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input         io_in_bits_wb_wen,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [3:0]  io_in_bits_wb_rd,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [31:0] io_in_bits_wdata,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input         io_in_bits_redirect_valid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [31:0] io_in_bits_redirect_dnpc,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [2:0]  io_in_bits_decode_funct3,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input         io_in_bits_decode_flags_1,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
                io_in_bits_decode_flags_2,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
                io_in_bits_decode_flags_3,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
                io_in_bits_npctrap_isEbreak,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [31:0] io_in_bits_npctrap_code,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_out_valid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [31:0] io_out_bits_wb_res,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_out_bits_wb_wen,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [3:0]  io_out_bits_wb_rd,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_out_bits_npctrap_isEbreak,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [31:0] io_out_bits_npctrap_code,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_out_bits_npctrap_isMMIO,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [31:0] io_mem_addr,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_mem_reqValid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [1:0]  io_mem_size,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input         io_mem_respValid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  input  [31:0] io_mem_rdata,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_mem_wen,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [31:0] io_mem_wdata,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [3:0]  io_mem_wmask,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output        io_redirect_valid,	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
  output [31:0] io_redirect_dnpc	// /home/yzh/projectn/npc/src/main/LSU.scala:7:14
);

  wire            _io_out_bits_wb_res_T_2 = |(io_in_bits_decode_funct3[1:0]);	// /home/yzh/projectn/npc/src/main/LSU.scala:20:30, :21:22
  wire            isLoadStore = io_in_bits_decode_flags_1 | io_in_bits_decode_flags_2;	// /home/yzh/projectn/npc/src/main/LSU.scala:22:28
  wire            isValidLoadStore = isLoadStore & io_in_valid;	// /home/yzh/projectn/npc/src/main/LSU.scala:22:28, :23:38
  reg             state;	// /home/yzh/projectn/npc/src/main/LSU.scala:29:22
  wire            _io_out_bits_wb_res_T =
    io_in_bits_decode_flags_1 & ~_io_out_bits_wb_res_T_2;	// /home/yzh/projectn/npc/src/main/LSU.scala:21:22, :46:13
  wire [3:0][7:0] _GEN =
    {{io_mem_rdata[31:24]},
     {io_mem_rdata[23:16]},
     {io_mem_rdata[15:8]},
     {io_mem_rdata[7:0]}};	// /home/yzh/projectn/npc/src/main/LSU.scala:42:40, :46:31
  wire            _io_out_bits_wb_res_T_3 =
    io_in_bits_decode_flags_1 & _io_out_bits_wb_res_T_2;	// /home/yzh/projectn/npc/src/main/LSU.scala:21:22, :47:13
  always @(posedge clock) begin	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
    if (reset)	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      state <= 1'h0;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :29:22
    else	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      state <= ~state & isValidLoadStore | state & ~io_mem_respValid;	// /home/yzh/projectn/npc/src/main/LSU.scala:21:22, :23:38, :29:22, :31:33, :32:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
    `ifdef FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      `FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      automatic logic [31:0] _RANDOM[0:0];	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      `ifdef INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
        `INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
        state = _RANDOM[/*Zero width*/ 1'b0][0];	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :29:22
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
      `FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_in_valid & ~isLoadStore | state & io_mem_respValid;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :22:28, :29:22, :56:{32,35,49}, :57:51
  assign io_out_bits_wb_res =
    (_io_out_bits_wb_res_T ? {24'h0, _GEN[io_in_bits_wb_res[1:0]]} : 32'h0)
    | (_io_out_bits_wb_res_T_3 ? io_mem_rdata : 32'h0)
    | (_io_out_bits_wb_res_T | _io_out_bits_wb_res_T_3 ? 32'h0 : io_in_bits_wb_res);	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :40:45, :46:{13,31}, :47:13, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:10
  assign io_out_bits_wb_wen = io_in_bits_wb_wen;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_out_bits_wb_rd = io_in_bits_wb_rd;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_out_bits_npctrap_isEbreak = io_in_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_out_bits_npctrap_code = io_in_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_out_bits_npctrap_isMMIO =
    io_in_bits_decode_flags_3 | isLoadStore & ~(io_in_bits_wb_res[31])
    & ~(io_in_bits_wb_res > 32'h2FFFFFFF & io_in_bits_wb_res < 32'h40000000);	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :22:28, :52:{31,47,50,55,60}, :53:{5,12,29,37}
  assign io_mem_addr = io_in_bits_wb_res;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_mem_reqValid = isValidLoadStore & ~state;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :23:38, :29:22, :35:39, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92
  assign io_mem_size = io_in_bits_decode_funct3[1:0];	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :20:30
  assign io_mem_wen = io_in_bits_decode_flags_2;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_mem_wdata =
    _io_out_bits_wb_res_T_2 ? io_in_bits_wdata : {4{io_in_bits_wdata[7:0]}};	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :21:22, :39:{22,35,47}
  assign io_mem_wmask = _io_out_bits_wb_res_T_2 ? 4'hF : 4'h1 << io_in_bits_wb_res[1:0];	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7, :21:22, :40:{22,38,45}
  assign io_redirect_valid = io_in_bits_redirect_valid;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
  assign io_redirect_dnpc = io_in_bits_redirect_dnpc;	// /home/yzh/projectn/npc/src/main/LSU.scala:6:7
endmodule

