// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module NPC(	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
  input         clock,	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
                reset,	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
  output [31:0] io_ifu_addr,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output        io_ifu_reqValid,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  input  [31:0] io_ifu_rdata,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  input         io_ifu_respValid,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output [31:0] io_lsu_addr,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output        io_lsu_reqValid,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output [1:0]  io_lsu_size,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  input         io_lsu_respValid,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  input  [31:0] io_lsu_rdata,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output        io_lsu_wen,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output [31:0] io_lsu_wdata,	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
  output [3:0]  io_lsu_wmask	// /home/yzh/projectn/npc/src/main/NPC.scala:34:14
);

  wire [31:0] _wbu_io_wb_res;	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
  wire        _wbu_io_wb_wen;	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
  wire [3:0]  _wbu_io_wb_rd;	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
  wire        _lsu_io_out_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire [31:0] _lsu_io_out_bits_wb_res;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire        _lsu_io_out_bits_wb_wen;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire [3:0]  _lsu_io_out_bits_wb_rd;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire        _lsu_io_out_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire [31:0] _lsu_io_out_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire        _lsu_io_out_bits_npctrap_isMMIO;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire        _lsu_io_redirect_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire [31:0] _lsu_io_redirect_dnpc;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  wire        _exu_io_out_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [31:0] _exu_io_out_bits_wb_res;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_wb_wen;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [3:0]  _exu_io_out_bits_wb_rd;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [31:0] _exu_io_out_bits_wdata;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_redirect_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [31:0] _exu_io_out_bits_redirect_dnpc;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [2:0]  _exu_io_out_bits_decode_funct3;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_decode_flags_1;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_decode_flags_2;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_decode_flags_3;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _exu_io_out_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire [31:0] _exu_io_out_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  wire        _idu_io_out_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [31:0] _idu_io_out_bits_src1;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [31:0] _idu_io_out_bits_src2;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [31:0] _idu_io_out_bits_src3;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_wen;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [3:0]  _idu_io_out_bits_rd;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [2:0]  _idu_io_out_bits_decode_funct3;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_decode_flags_0;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_decode_flags_1;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_decode_flags_2;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_decode_flags_3;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _idu_io_out_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire [31:0] _idu_io_out_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  wire        _ifu_io_out_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
  wire [31:0] _ifu_io_out_bits_inst;	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
  wire [31:0] _ifu_io_out_bits_snpc;	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
  reg         view__REG_isEbreak;	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
  reg  [31:0] view__REG_code;	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
  reg         view__REG_isMMIO;	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
  reg         npctrap_valid_REG;	// /home/yzh/projectn/npc/src/main/NPC.scala:63:32
  always @(posedge clock) begin	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
    view__REG_isEbreak <= _lsu_io_out_bits_npctrap_isEbreak;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19, :62:26
    view__REG_code <= _lsu_io_out_bits_npctrap_code;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19, :62:26
    view__REG_isMMIO <= _lsu_io_out_bits_npctrap_isMMIO;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19, :62:26
    npctrap_valid_REG <= _lsu_io_out_valid;	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19, :63:32
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
    `ifdef FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
      `FIRRTL_BEFORE_INITIAL	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
    `endif // FIRRTL_BEFORE_INITIAL
    initial begin	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
      automatic logic [31:0] _RANDOM[0:1];	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
      `ifdef INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
        `INIT_RANDOM_PROLOG_	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
        for (logic [1:0] i = 2'h0; i < 2'h2; i += 2'h1) begin
          _RANDOM[i[0]] = `RANDOM;	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
        end	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
        view__REG_isEbreak = _RANDOM[1'h0][1];	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7, :62:26
        view__REG_code = {_RANDOM[1'h0][31:2], _RANDOM[1'h1][1:0]};	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7, :62:26
        view__REG_isMMIO = _RANDOM[1'h1][2];	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7, :62:26
        npctrap_valid_REG = _RANDOM[1'h1][3];	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7, :62:26, :63:32
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
      `FIRRTL_AFTER_INITIAL	// /home/yzh/projectn/npc/src/main/NPC.scala:33:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  IFU ifu (	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
    .clock             (clock),
    .reset             (reset),
    .io_mem_addr       (io_ifu_addr),
    .io_mem_reqValid   (io_ifu_reqValid),
    .io_mem_rdata      (io_ifu_rdata),
    .io_mem_respValid  (io_ifu_respValid),
    .io_out_valid      (_ifu_io_out_valid),
    .io_out_bits_inst  (_ifu_io_out_bits_inst),
    .io_out_bits_snpc  (_ifu_io_out_bits_snpc),
    .io_redirect_valid (_lsu_io_redirect_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_redirect_dnpc  (_lsu_io_redirect_dnpc),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_nextInst       (_lsu_io_out_valid)	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
  IDU idu (	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .clock                        (clock),
    .reset                        (reset),
    .io_in_valid                  (_ifu_io_out_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
    .io_in_bits_inst              (_ifu_io_out_bits_inst),	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
    .io_in_bits_snpc              (_ifu_io_out_bits_snpc),	// /home/yzh/projectn/npc/src/main/NPC.scala:43:19
    .io_out_valid                 (_idu_io_out_valid),
    .io_out_bits_src1             (_idu_io_out_bits_src1),
    .io_out_bits_src2             (_idu_io_out_bits_src2),
    .io_out_bits_src3             (_idu_io_out_bits_src3),
    .io_out_bits_wen              (_idu_io_out_bits_wen),
    .io_out_bits_rd               (_idu_io_out_bits_rd),
    .io_out_bits_decode_funct3    (_idu_io_out_bits_decode_funct3),
    .io_out_bits_decode_flags_0   (_idu_io_out_bits_decode_flags_0),
    .io_out_bits_decode_flags_1   (_idu_io_out_bits_decode_flags_1),
    .io_out_bits_decode_flags_2   (_idu_io_out_bits_decode_flags_2),
    .io_out_bits_decode_flags_3   (_idu_io_out_bits_decode_flags_3),
    .io_out_bits_npctrap_isEbreak (_idu_io_out_bits_npctrap_isEbreak),
    .io_out_bits_npctrap_code     (_idu_io_out_bits_npctrap_code),
    .io_wb_res                    (_wbu_io_wb_res),	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
    .io_wb_wen                    (_wbu_io_wb_wen),	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
    .io_wb_rd                     (_wbu_io_wb_rd)	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
  EXU exu (	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_valid                  (_idu_io_out_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_src1              (_idu_io_out_bits_src1),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_src2              (_idu_io_out_bits_src2),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_src3              (_idu_io_out_bits_src3),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_wen               (_idu_io_out_bits_wen),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_rd                (_idu_io_out_bits_rd),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_decode_funct3     (_idu_io_out_bits_decode_funct3),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_decode_flags_0    (_idu_io_out_bits_decode_flags_0),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_decode_flags_1    (_idu_io_out_bits_decode_flags_1),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_decode_flags_2    (_idu_io_out_bits_decode_flags_2),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_decode_flags_3    (_idu_io_out_bits_decode_flags_3),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_npctrap_isEbreak  (_idu_io_out_bits_npctrap_isEbreak),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_in_bits_npctrap_code      (_idu_io_out_bits_npctrap_code),	// /home/yzh/projectn/npc/src/main/NPC.scala:44:19
    .io_out_valid                 (_exu_io_out_valid),
    .io_out_bits_wb_res           (_exu_io_out_bits_wb_res),
    .io_out_bits_wb_wen           (_exu_io_out_bits_wb_wen),
    .io_out_bits_wb_rd            (_exu_io_out_bits_wb_rd),
    .io_out_bits_wdata            (_exu_io_out_bits_wdata),
    .io_out_bits_redirect_valid   (_exu_io_out_bits_redirect_valid),
    .io_out_bits_redirect_dnpc    (_exu_io_out_bits_redirect_dnpc),
    .io_out_bits_decode_funct3    (_exu_io_out_bits_decode_funct3),
    .io_out_bits_decode_flags_1   (_exu_io_out_bits_decode_flags_1),
    .io_out_bits_decode_flags_2   (_exu_io_out_bits_decode_flags_2),
    .io_out_bits_decode_flags_3   (_exu_io_out_bits_decode_flags_3),
    .io_out_bits_npctrap_isEbreak (_exu_io_out_bits_npctrap_isEbreak),
    .io_out_bits_npctrap_code     (_exu_io_out_bits_npctrap_code)
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
  LSU lsu (	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .clock                        (clock),
    .reset                        (reset),
    .io_in_valid                  (_exu_io_out_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_wb_res            (_exu_io_out_bits_wb_res),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_wb_wen            (_exu_io_out_bits_wb_wen),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_wb_rd             (_exu_io_out_bits_wb_rd),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_wdata             (_exu_io_out_bits_wdata),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_redirect_valid    (_exu_io_out_bits_redirect_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_redirect_dnpc     (_exu_io_out_bits_redirect_dnpc),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_decode_funct3     (_exu_io_out_bits_decode_funct3),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_decode_flags_1    (_exu_io_out_bits_decode_flags_1),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_decode_flags_2    (_exu_io_out_bits_decode_flags_2),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_decode_flags_3    (_exu_io_out_bits_decode_flags_3),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_npctrap_isEbreak  (_exu_io_out_bits_npctrap_isEbreak),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_in_bits_npctrap_code      (_exu_io_out_bits_npctrap_code),	// /home/yzh/projectn/npc/src/main/NPC.scala:45:19
    .io_out_valid                 (_lsu_io_out_valid),
    .io_out_bits_wb_res           (_lsu_io_out_bits_wb_res),
    .io_out_bits_wb_wen           (_lsu_io_out_bits_wb_wen),
    .io_out_bits_wb_rd            (_lsu_io_out_bits_wb_rd),
    .io_out_bits_npctrap_isEbreak (_lsu_io_out_bits_npctrap_isEbreak),
    .io_out_bits_npctrap_code     (_lsu_io_out_bits_npctrap_code),
    .io_out_bits_npctrap_isMMIO   (_lsu_io_out_bits_npctrap_isMMIO),
    .io_mem_addr                  (io_lsu_addr),
    .io_mem_reqValid              (io_lsu_reqValid),
    .io_mem_size                  (io_lsu_size),
    .io_mem_respValid             (io_lsu_respValid),
    .io_mem_rdata                 (io_lsu_rdata),
    .io_mem_wen                   (io_lsu_wen),
    .io_mem_wdata                 (io_lsu_wdata),
    .io_mem_wmask                 (io_lsu_wmask),
    .io_redirect_valid            (_lsu_io_redirect_valid),
    .io_redirect_dnpc             (_lsu_io_redirect_dnpc)
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
  WBU wbu (	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
    .io_in_valid       (_lsu_io_out_valid),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_in_bits_wb_res (_lsu_io_out_bits_wb_res),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_in_bits_wb_wen (_lsu_io_out_bits_wb_wen),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_in_bits_wb_rd  (_lsu_io_out_bits_wb_rd),	// /home/yzh/projectn/npc/src/main/NPC.scala:46:19
    .io_wb_res         (_wbu_io_wb_res),
    .io_wb_wen         (_wbu_io_wb_wen),
    .io_wb_rd          (_wbu_io_wb_rd)
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:47:19
  NPCTrap npctrap (	// /home/yzh/projectn/npc/src/main/NPC.scala:61:25
    .valid    (npctrap_valid_REG),	// /home/yzh/projectn/npc/src/main/NPC.scala:63:32
    .isEbreak (view__REG_isEbreak),	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
    .code     (view__REG_code),	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
    .isMMIO   (view__REG_isMMIO)	// /home/yzh/projectn/npc/src/main/NPC.scala:62:26
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:61:25
endmodule

