// Generated by CIRCT firtool-1.155.0
module Top(	// /home/yzh/projectn/npc/src/main/NPC.scala:67:7
  input clock,	// /home/yzh/projectn/npc/src/main/NPC.scala:67:7
        reset	// /home/yzh/projectn/npc/src/main/NPC.scala:67:7
);

  wire [31:0] _mem_imem_rdata;	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
  wire        _mem_imem_respValid;	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
  wire        _mem_dmem_respValid;	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
  wire [31:0] _mem_dmem_rdata;	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
  wire [31:0] _npc_io_ifu_addr;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire        _npc_io_ifu_reqValid;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire [31:0] _npc_io_lsu_addr;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire        _npc_io_lsu_reqValid;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire [1:0]  _npc_io_lsu_size;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire        _npc_io_lsu_wen;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire [31:0] _npc_io_lsu_wdata;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  wire [3:0]  _npc_io_lsu_wmask;	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  NPC npc (	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .clock            (clock),
    .reset            (reset),
    .io_ifu_addr      (_npc_io_ifu_addr),
    .io_ifu_reqValid  (_npc_io_ifu_reqValid),
    .io_ifu_rdata     (_mem_imem_rdata),	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
    .io_ifu_respValid (_mem_imem_respValid),	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
    .io_lsu_addr      (_npc_io_lsu_addr),
    .io_lsu_reqValid  (_npc_io_lsu_reqValid),
    .io_lsu_size      (_npc_io_lsu_size),
    .io_lsu_respValid (_mem_dmem_respValid),	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
    .io_lsu_rdata     (_mem_dmem_rdata),	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
    .io_lsu_wen       (_npc_io_lsu_wen),
    .io_lsu_wdata     (_npc_io_lsu_wdata),
    .io_lsu_wmask     (_npc_io_lsu_wmask)
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  SimMem mem (	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
    .clock          (clock),
    .imem_addr      (_npc_io_ifu_addr),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .imem_reqValid  (_npc_io_ifu_reqValid),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .imem_rdata     (_mem_imem_rdata),
    .imem_respValid (_mem_imem_respValid),
    .dmem_addr      (_npc_io_lsu_addr),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .dmem_reqValid  (_npc_io_lsu_reqValid),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .dmem_size      (_npc_io_lsu_size),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .dmem_respValid (_mem_dmem_respValid),
    .dmem_rdata     (_mem_dmem_rdata),
    .dmem_wen       (_npc_io_lsu_wen),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .dmem_wdata     (_npc_io_lsu_wdata),	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
    .dmem_wmask     (_npc_io_lsu_wmask)	// /home/yzh/projectn/npc/src/main/NPC.scala:68:19
  );	// /home/yzh/projectn/npc/src/main/NPC.scala:69:19
endmodule

