// Generated by CIRCT firtool-1.155.0
module WBU(	// /home/yzh/projectn/npc/src/main/WBU.scala:5:7
  input         io_in_valid,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  input  [31:0] io_in_bits_wb_res,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  input         io_in_bits_wb_wen,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  input  [3:0]  io_in_bits_wb_rd,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  output [31:0] io_wb_res,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  output        io_wb_wen,	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
  output [3:0]  io_wb_rd	// /home/yzh/projectn/npc/src/main/WBU.scala:6:14
);

  assign io_wb_res = io_in_bits_wb_res;	// /home/yzh/projectn/npc/src/main/WBU.scala:5:7
  assign io_wb_wen = io_in_bits_wb_wen & io_in_valid;	// /home/yzh/projectn/npc/src/main/WBU.scala:5:7, :11:34
  assign io_wb_rd = io_in_bits_wb_rd;	// /home/yzh/projectn/npc/src/main/WBU.scala:5:7
endmodule

