// Generated by CIRCT firtool-1.155.0
module MCU_NPC(	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  input         clock,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
                reset,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
                io_master_awready,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_awvalid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [31:0] io_master_awaddr,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [2:0]  io_master_awsize,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_awid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [7:0]  io_master_awlen,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [1:0]  io_master_awburst,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input         io_master_wready,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_wvalid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [31:0] io_master_wdata,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [3:0]  io_master_wstrb,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_wlast,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
                io_master_bready,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input         io_master_bvalid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input  [1:0]  io_master_bresp,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input         io_master_bid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
                io_master_arready,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_arvalid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [31:0] io_master_araddr,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [2:0]  io_master_arsize,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_arid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [7:0]  io_master_arlen,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output [1:0]  io_master_arburst,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  output        io_master_rready,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input         io_master_rvalid,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input  [1:0]  io_master_rresp,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input  [31:0] io_master_rdata,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
  input         io_master_rlast,	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
                io_master_rid	// @[/home/yzh/projectn/npc/src/main/NPC.scala:34:14]
);

  wire        _xbar_io_in_0_awready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire        _xbar_io_in_0_bvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire        _xbar_io_in_0_arready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire        _xbar_io_in_0_rvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire [31:0] _xbar_io_in_0_rdata;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire        _xbar_io_in_1_arready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire        _xbar_io_in_1_rvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire [31:0] _xbar_io_in_1_rdata;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  wire [31:0] _wbu_io_wb_res;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
  wire        _wbu_io_wb_wen;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
  wire [3:0]  _wbu_io_wb_rd;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
  wire        _lsu_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [31:0] _lsu_io_out_bits_wb_res;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_out_bits_wb_wen;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [3:0]  _lsu_io_out_bits_wb_rd;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_mem_awvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [31:0] _lsu_io_mem_awaddr;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [2:0]  _lsu_io_mem_awsize;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [31:0] _lsu_io_mem_wdata;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [3:0]  _lsu_io_mem_wstrb;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_mem_bready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_mem_arvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [31:0] _lsu_io_mem_araddr;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [2:0]  _lsu_io_mem_arsize;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_mem_rready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _lsu_io_redirect_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire [31:0] _lsu_io_redirect_dnpc;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  wire        _exu_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire [31:0] _exu_io_out_bits_wb_res;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire        _exu_io_out_bits_wb_wen;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire [3:0]  _exu_io_out_bits_wb_rd;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire [31:0] _exu_io_out_bits_wdata;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire        _exu_io_out_bits_redirect_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire [31:0] _exu_io_out_bits_redirect_dnpc;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire [2:0]  _exu_io_out_bits_decode_funct3;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire        _exu_io_out_bits_decode_flags_1;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire        _exu_io_out_bits_decode_flags_2;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  wire        _idu_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire [31:0] _idu_io_out_bits_src1;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire [31:0] _idu_io_out_bits_src2;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire [31:0] _idu_io_out_bits_src3;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_wen;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire [3:0]  _idu_io_out_bits_rd;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire [2:0]  _idu_io_out_bits_decode_funct3;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_0;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_1;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_2;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_3;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_4;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_5;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _idu_io_out_bits_decode_flags_6;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  wire        _ifu_io_mem_arvalid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire [31:0] _ifu_io_mem_araddr;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire        _ifu_io_mem_rready;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire        _ifu_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire [31:0] _ifu_io_out_bits_inst;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire [31:0] _ifu_io_out_bits_pc;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  wire [31:0] _ifu_io_out_bits_snpc;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  MCU_IFU ifu (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .clock               (clock),
    .reset               (reset),
    .io_mem_arready     (_xbar_io_in_1_arready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_arvalid     (_ifu_io_mem_arvalid),
    .io_mem_araddr (_ifu_io_mem_araddr),
    .io_mem_rready      (_ifu_io_mem_rready),
    .io_mem_rvalid      (_xbar_io_in_1_rvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_rdata  (_xbar_io_in_1_rdata),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_out_valid        (_ifu_io_out_valid),
    .io_out_bits_inst    (_ifu_io_out_bits_inst),
    .io_out_bits_pc      (_ifu_io_out_bits_pc),
    .io_out_bits_snpc    (_ifu_io_out_bits_snpc),
    .io_redirect_valid   (_lsu_io_redirect_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_redirect_dnpc    (_lsu_io_redirect_dnpc),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_nextInst         (_lsu_io_out_valid)	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
  MCU_IDU idu (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_valid                (_ifu_io_out_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_bits_inst            (_ifu_io_out_bits_inst),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_bits_pc              (_ifu_io_out_bits_pc),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_bits_snpc            (_ifu_io_out_bits_snpc),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_out_valid               (_idu_io_out_valid),
    .io_out_bits_src1           (_idu_io_out_bits_src1),
    .io_out_bits_src2           (_idu_io_out_bits_src2),
    .io_out_bits_src3           (_idu_io_out_bits_src3),
    .io_out_bits_wen            (_idu_io_out_bits_wen),
    .io_out_bits_rd             (_idu_io_out_bits_rd),
    .io_out_bits_decode_funct3  (_idu_io_out_bits_decode_funct3),
    .io_out_bits_decode_flags_0 (_idu_io_out_bits_decode_flags_0),
    .io_out_bits_decode_flags_1 (_idu_io_out_bits_decode_flags_1),
    .io_out_bits_decode_flags_2 (_idu_io_out_bits_decode_flags_2),
    .io_out_bits_decode_flags_3 (_idu_io_out_bits_decode_flags_3),
    .io_out_bits_decode_flags_4 (_idu_io_out_bits_decode_flags_4),
    .io_out_bits_decode_flags_5 (_idu_io_out_bits_decode_flags_5),
    .io_out_bits_decode_flags_6 (_idu_io_out_bits_decode_flags_6),
    .io_wb_res                  (_wbu_io_wb_res),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
    .io_wb_wen                  (_wbu_io_wb_wen),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
    .io_wb_rd                   (_wbu_io_wb_rd)	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
  MCU_EXU exu (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .clock                      (clock),
    .reset                      (reset),
    .io_in_valid                (_idu_io_out_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_src1            (_idu_io_out_bits_src1),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_src2            (_idu_io_out_bits_src2),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_src3            (_idu_io_out_bits_src3),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_wen             (_idu_io_out_bits_wen),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_rd              (_idu_io_out_bits_rd),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_funct3   (_idu_io_out_bits_decode_funct3),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_0  (_idu_io_out_bits_decode_flags_0),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_1  (_idu_io_out_bits_decode_flags_1),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_2  (_idu_io_out_bits_decode_flags_2),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_3  (_idu_io_out_bits_decode_flags_3),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_4  (_idu_io_out_bits_decode_flags_4),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_5  (_idu_io_out_bits_decode_flags_5),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_in_bits_decode_flags_6  (_idu_io_out_bits_decode_flags_6),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:44:19]
    .io_out_valid               (_exu_io_out_valid),
    .io_out_bits_wb_res         (_exu_io_out_bits_wb_res),
    .io_out_bits_wb_wen         (_exu_io_out_bits_wb_wen),
    .io_out_bits_wb_rd          (_exu_io_out_bits_wb_rd),
    .io_out_bits_wdata          (_exu_io_out_bits_wdata),
    .io_out_bits_redirect_valid (_exu_io_out_bits_redirect_valid),
    .io_out_bits_redirect_dnpc  (_exu_io_out_bits_redirect_dnpc),
    .io_out_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),
    .io_out_bits_decode_flags_1 (_exu_io_out_bits_decode_flags_1),
    .io_out_bits_decode_flags_2 (_exu_io_out_bits_decode_flags_2)
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
  MCU_LSU lsu (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .clock                     (clock),
    .reset                     (reset),
    .io_in_valid               (_exu_io_out_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_wb_res         (_exu_io_out_bits_wb_res),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_wb_wen         (_exu_io_out_bits_wb_wen),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_wb_rd          (_exu_io_out_bits_wb_rd),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_wdata          (_exu_io_out_bits_wdata),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_redirect_valid (_exu_io_out_bits_redirect_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_redirect_dnpc  (_exu_io_out_bits_redirect_dnpc),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_decode_funct3  (_exu_io_out_bits_decode_funct3),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_decode_flags_1 (_exu_io_out_bits_decode_flags_1),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_in_bits_decode_flags_2 (_exu_io_out_bits_decode_flags_2),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:45:19]
    .io_out_valid              (_lsu_io_out_valid),
    .io_out_bits_wb_res        (_lsu_io_out_bits_wb_res),
    .io_out_bits_wb_wen        (_lsu_io_out_bits_wb_wen),
    .io_out_bits_wb_rd         (_lsu_io_out_bits_wb_rd),
    .io_mem_awready           (_xbar_io_in_0_awready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_awvalid           (_lsu_io_mem_awvalid),
    .io_mem_awaddr       (_lsu_io_mem_awaddr),
    .io_mem_awsize       (_lsu_io_mem_awsize),
    .io_mem_wdata        (_lsu_io_mem_wdata),
    .io_mem_wstrb        (_lsu_io_mem_wstrb),
    .io_mem_bready            (_lsu_io_mem_bready),
    .io_mem_bvalid            (_xbar_io_in_0_bvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_arready           (_xbar_io_in_0_arready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_arvalid           (_lsu_io_mem_arvalid),
    .io_mem_araddr       (_lsu_io_mem_araddr),
    .io_mem_arsize       (_lsu_io_mem_arsize),
    .io_mem_rready            (_lsu_io_mem_rready),
    .io_mem_rvalid            (_xbar_io_in_0_rvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_mem_rdata        (_xbar_io_in_0_rdata),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .io_redirect_valid         (_lsu_io_redirect_valid),
    .io_redirect_dnpc          (_lsu_io_redirect_dnpc)
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
  MCU_WBU wbu (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
    .io_in_valid       (_lsu_io_out_valid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_bits_wb_res (_lsu_io_out_bits_wb_res),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_bits_wb_wen (_lsu_io_out_bits_wb_wen),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_bits_wb_rd  (_lsu_io_out_bits_wb_rd),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_wb_res         (_wbu_io_wb_res),
    .io_wb_wen         (_wbu_io_wb_wen),
    .io_wb_rd          (_wbu_io_wb_rd)
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:47:19]
  MCU_AXI4LiteCrossbarNto1 xbar (	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
    .clock                (clock),
    .reset                (reset),
    .io_in_0_awready     (_xbar_io_in_0_awready),
    .io_in_0_awvalid     (_lsu_io_mem_awvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_awaddr (_lsu_io_mem_awaddr),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_awsize (_lsu_io_mem_awsize),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_wdata  (_lsu_io_mem_wdata),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_wstrb  (_lsu_io_mem_wstrb),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_bready      (_lsu_io_mem_bready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_bvalid      (_xbar_io_in_0_bvalid),
    .io_in_0_arready     (_xbar_io_in_0_arready),
    .io_in_0_arvalid     (_lsu_io_mem_arvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_araddr (_lsu_io_mem_araddr),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_arsize (_lsu_io_mem_arsize),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_rready      (_lsu_io_mem_rready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:46:19]
    .io_in_0_rvalid      (_xbar_io_in_0_rvalid),
    .io_in_0_rdata  (_xbar_io_in_0_rdata),
    .io_in_1_arready     (_xbar_io_in_1_arready),
    .io_in_1_arvalid     (_ifu_io_mem_arvalid),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_1_araddr (_ifu_io_mem_araddr),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_1_rready      (_ifu_io_mem_rready),	// @[/home/yzh/projectn/npc/src/main/NPC.scala:43:19]
    .io_in_1_rvalid      (_xbar_io_in_1_rvalid),
    .io_in_1_rdata  (_xbar_io_in_1_rdata),
    .io_out_awready      (io_master_awready),
    .io_out_awvalid      (io_master_awvalid),
    .io_out_awaddr  (io_master_awaddr),
    .io_out_awsize  (io_master_awsize),
    .io_out_wvalid       (io_master_wvalid),
    .io_out_wdata   (io_master_wdata),
    .io_out_wstrb   (io_master_wstrb),
    .io_out_bready       (io_master_bready),
    .io_out_bvalid       (io_master_bvalid),
    .io_out_arready      (io_master_arready),
    .io_out_arvalid      (io_master_arvalid),
    .io_out_araddr  (io_master_araddr),
    .io_out_arsize  (io_master_arsize),
    .io_out_rready       (io_master_rready),
    .io_out_rvalid       (io_master_rvalid),
    .io_out_rdata   (io_master_rdata)
  );	// @[/home/yzh/projectn/npc/src/main/NPC.scala:58:20]
  assign io_master_awid = 1'h0;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_awlen = 8'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:105:23, /home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_awburst = 2'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:105:23, /home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_wlast = 1'h1;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_arid = 1'h0;	// @[/home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_arlen = 8'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:105:23, /home/yzh/projectn/npc/src/main/NPC.scala:33:7]
  assign io_master_arburst = 2'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:105:23, /home/yzh/projectn/npc/src/main/NPC.scala:33:7]
endmodule

