// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MCU_IDU(	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
  input         clock,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
                reset,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
                io_in_valid,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  input  [31:0] io_in_bits_inst,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_in_bits_pc,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_in_bits_snpc,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output        io_out_valid,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output [31:0] io_out_bits_src1,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_src2,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_src3,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output        io_out_bits_wen,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output [3:0]  io_out_bits_rd,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  output        io_out_bits_decode_flags_0,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_1,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_2,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_3,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_4,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_5,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
                io_out_bits_decode_flags_6,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  input  [31:0] io_wb_res,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  input         io_wb_wen,	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
  input  [3:0]  io_wb_rd	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14]
);

  wire        isJal = io_in_bits_inst[6:2] == 5'h1B;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :20:24]
  wire        isAuipc = io_in_bits_inst[6:2] == 5'h5;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :23:24]
  wire        isStore = io_in_bits_inst[6:2] == 5'h8;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :25:24]
  wire        _useALU_T_3 = |(io_in_bits_inst[14:12]);	// @[/home/yzh/projectn/npc/src/main/IDU.scala:18:20, :26:51]
  wire        isRtype = io_in_bits_inst[6:2] == 5'hC;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :28:25]
  wire        isBtype = io_in_bits_inst[6:2] == 5'h18;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :29:25]
  wire        isUtype = io_in_bits_inst[6:2] == 5'hD | isAuipc;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :22:24, :23:24, :30:23]
  reg  [31:0] R_1;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_2;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_3;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_4;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_5;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_6;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_7;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_8;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_9;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_10;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_11;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_12;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_13;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_14;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  reg  [31:0] R_15;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  wire [31:0] rs2Val =
    (io_in_bits_inst[24:20] == 5'h1 ? R_1 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h2 ? R_2 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h3 ? R_3 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h4 ? R_4 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h5 ? R_5 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h6 ? R_6 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h7 ? R_7 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h8 ? R_8 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'h9 ? R_9 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hA ? R_10 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hB ? R_11 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hC ? R_12 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hD ? R_13 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hE ? R_14 : 32'h0)
    | (io_in_bits_inst[24:20] == 5'hF ? R_15 : 32'h0);	// @[/home/yzh/projectn/npc/src/main/IDU.scala:22:24, :23:24, :25:24, :28:25, :41:25, :44:59, :45:{66,84,107}, :56:17]
  wire        src2Reg = isRtype | isBtype;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:28:25, :29:25, :61:25]
  wire        _io_out_bits_src1_T = isAuipc | isJal;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:20:24, :23:24, :64:14]
  wire        _io_out_bits_wen_T = io_in_bits_inst[6:2] != 5'h8;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:17:20, :25:24, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:44]
  wire [14:0] _GEN =
    {io_in_bits_inst[31:25], io_in_bits_inst[14:12], io_in_bits_inst[6:2]};	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14, /home/yzh/projectn/npc/src/main/Inst.scala:66:28, src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [9:0]  _GEN_0 = {io_in_bits_inst[14:12], io_in_bits_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [16:0] _GEN_1 =
    {io_in_bits_inst[31:25], io_in_bits_inst[14:12], io_in_bits_inst[6:0]};	// @[/home/yzh/projectn/npc/src/main/IDU.scala:7:14, src/main/scala/chisel3/util/Lookup.scala:31:38]
  always @(posedge clock) begin	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
    if (~reset)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:33:9]
      assert__chisel3_builtin:
        assert(~(io_in_valid
                 & ~(_GEN_0 == 10'h13 | _GEN_1 == 17'h93 | _GEN_0 == 10'h113
                     | _GEN_0 == 10'h193 | _GEN_0 == 10'h213 | _GEN_1 == 17'h293
                     | _GEN_0 == 10'h313 | _GEN_0 == 10'h393 | _GEN_1 == 17'h8293
                     | _GEN_1 == 17'h33 | _GEN_1 == 17'hB3 | _GEN_1 == 17'h133
                     | _GEN_1 == 17'h1B3 | _GEN_1 == 17'h233 | _GEN_1 == 17'h2B3
                     | _GEN_1 == 17'h333 | _GEN_1 == 17'h3B3 | _GEN_1 == 17'h8033
                     | _GEN_1 == 17'h82B3 | io_in_bits_inst[6:0] == 7'h17
                     | io_in_bits_inst[6:0] == 7'h37 | _GEN_0 == 10'h67
                     | io_in_bits_inst[6:0] == 7'h6F | _GEN_0 == 10'h63 | _GEN_0 == 10'hE3
                     | _GEN_0 == 10'h263 | _GEN_0 == 10'h2E3 | _GEN_0 == 10'h363
                     | _GEN_0 == 10'h3E3 | _GEN_0 == 10'h3 | _GEN_0 == 10'h83
                     | _GEN_0 == 10'h103 | _GEN_0 == 10'h203 | _GEN_0 == 10'h283
                     | _GEN_0 == 10'h23 | _GEN_0 == 10'hA3 | _GEN_0 == 10'h123
                     | _GEN_0 == 10'h173) & io_in_bits_inst != 32'h100073))
        else $error("Assertion failed: pc = 0x%x, inst = 0x%x\n\n",
                    io_in_bits_snpc - 32'h4, io_in_bits_inst);	// @[/home/yzh/projectn/npc/src/main/IDU.scala:24:24, :33:{9,10,24,86}, src/main/scala/chisel3/util/Lookup.scala:31:38, :33:37]
    if (io_wb_wen & io_wb_rd == 4'h1)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_1 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h2)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_2 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h3)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_3 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h4)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_4 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h5)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_5 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h6)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_6 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h7)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_7 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h8)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_8 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'h9)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_9 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'hA)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_10 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'hB)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_11 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'hC)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_12 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'hD)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_13 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & io_wb_rd == 4'hE)	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59, :46:{98,107,111}, :74:20]
      R_14 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
    if (io_wb_wen & (&io_wb_rd))	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59, :46:{98,107,111}, :74:20]
      R_15 <= io_wb_res;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:44:59]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:14];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
    initial begin	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
        for (logic [3:0] i = 4'h0; i < 4'hF; i += 4'h1) begin
          _RANDOM[i] = `RANDOM;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
        end	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
        R_1 = _RANDOM[4'h0];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_2 = _RANDOM[4'h1];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_3 = _RANDOM[4'h2];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_4 = _RANDOM[4'h3];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_5 = _RANDOM[4'h4];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_6 = _RANDOM[4'h5];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_7 = _RANDOM[4'h6];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_8 = _RANDOM[4'h7];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_9 = _RANDOM[4'h8];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_10 = _RANDOM[4'h9];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_11 = _RANDOM[4'hA];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_12 = _RANDOM[4'hB];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_13 = _RANDOM[4'hC];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_14 = _RANDOM[4'hD];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
        R_15 = _RANDOM[4'hE];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :44:59]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_in_valid;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7]
  assign io_out_bits_src1 =
    (_io_out_bits_src1_T ? io_in_bits_pc : 32'h0)
    | (io_in_bits_inst[6:2] != 5'hD & ~_io_out_bits_src1_T
         ? (io_in_bits_inst[19:15] == 5'h1 ? R_1 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h2 ? R_2 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h3 ? R_3 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h4 ? R_4 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h5 ? R_5 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h6 ? R_6 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h7 ? R_7 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h8 ? R_8 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'h9 ? R_9 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hA ? R_10 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hB ? R_11 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hC ? R_12 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hD ? R_13 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hE ? R_14 : 32'h0)
           | (io_in_bits_inst[19:15] == 5'hF ? R_15 : 32'h0)
         : 32'h0);	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :22:24, :23:24, :25:24, :28:25, :41:25, :44:59, :45:{66,84,107}, :55:37, :64:14, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:{10,44,60}]
  assign io_out_bits_src2 =
    (src2Reg ? rs2Val : 32'h0)
    | (isStore
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:25], io_in_bits_inst[11:7]}
         : 32'h0) | (isUtype ? {io_in_bits_inst[31:12], 12'h0} : 32'h0)
    | (isJal
         ? {{12{io_in_bits_inst[31]}},
            io_in_bits_inst[19:12],
            io_in_bits_inst[20],
            io_in_bits_inst[30:21],
            1'h0}
         : 32'h0)
    | (~src2Reg & _io_out_bits_wen_T & ~isUtype & io_in_bits_inst[6:2] != 5'h1B
         ? {{20{io_in_bits_inst[31]}}, io_in_bits_inst[31:20]}
         : 32'h0);	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :20:24, :24:24, :25:24, :30:23, :35:26, :36:{18,26}, :37:{26,41}, :38:{26,38,53,65}, :45:107, :61:25, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:{10,44,60}, :23:{34,49}, :28:47]
  assign io_out_bits_src3 =
    isStore
      ? rs2Val
      : isBtype
          ? io_in_bits_pc
            + {{20{io_in_bits_inst[31]}},
               io_in_bits_inst[7],
               io_in_bits_inst[30:25],
               io_in_bits_inst[11:8],
               1'h0}
          : io_in_bits_snpc;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :24:24, :25:24, :29:25, :38:26, :39:{38,49,64}, :45:107, :72:{18,39,55}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:23:49]
  assign io_out_bits_wen = _io_out_bits_wen_T & io_in_bits_inst[6:2] != 5'h18;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :25:24, :29:25, :76:{23,26}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:11:44]
  assign io_out_bits_rd = io_in_bits_inst[10:7];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :37:41, :77:16]
  assign io_out_bits_decode_funct3 = io_in_bits_inst[14:12];	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :18:20]
  assign io_out_bits_decode_flags_0 = isJal | io_in_bits_inst[6:2] == 5'h19;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :20:24, :21:24, :80:24]
  assign io_out_bits_decode_flags_1 = io_in_bits_inst[6:2] == 5'h0;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :24:24]
  assign io_out_bits_decode_flags_2 = isStore;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :25:24]
  assign io_out_bits_decode_flags_3 = io_in_bits_inst[6:2] == 5'h1C & _useALU_T_3;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :26:{24,40,51}]
  assign io_out_bits_decode_flags_4 = isBtype;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :29:25]
  assign io_out_bits_decode_flags_5 =
    (io_in_bits_inst[6:2] == 5'h4 | isRtype) & _useALU_T_3;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, :17:20, :26:51, :28:25, :41:{25,41,69}]
  assign io_out_bits_decode_flags_6 =
    _GEN == 15'h200C | _GEN == 15'h20AC | _GEN == 15'h20A4;	// @[/home/yzh/projectn/npc/src/main/IDU.scala:6:7, /home/yzh/projectn/npc/src/main/Inst.scala:66:28, :67:14, :70:38, src/main/scala/chisel3/util/Lookup.scala:31:38]
endmodule

