// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MCU_LSU(	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  input         clock,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
                reset,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
                io_in_valid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_wb_res,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_in_bits_wb_wen,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [3:0]  io_in_bits_wb_rd,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_wdata,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_in_bits_redirect_valid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [31:0] io_in_bits_redirect_dnpc,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_in_bits_decode_flags_1,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
                io_in_bits_decode_flags_2,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_out_valid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [31:0] io_out_bits_wb_res,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_out_bits_wb_wen,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [3:0]  io_out_bits_wb_rd,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_mem_awready,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_mem_awvalid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [31:0] io_mem_awaddr,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [2:0]  io_mem_awsize,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [31:0] io_mem_wdata,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [3:0]  io_mem_wstrb,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_mem_bready,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_mem_bvalid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
                io_mem_arready,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_mem_arvalid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [31:0] io_mem_araddr,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [2:0]  io_mem_arsize,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_mem_rready,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input         io_mem_rvalid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  input  [31:0] io_mem_rdata,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output        io_redirect_valid,	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
  output [31:0] io_redirect_dnpc	// @[/home/yzh/projectn/npc/src/main/LSU.scala:7:14]
);

  wire        io_mem_bready_0;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        io_mem_rready_0;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  reg  [2:0]  state;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22]
  wire        _memFinish_T = io_mem_rready_0 & io_mem_rvalid;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  wire        _memFinish_T_1 = io_mem_bready_0 & io_mem_bvalid;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  wire        _io_mem_awvalid_T = state == 3'h0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _io_mem_arvalid_T_3 = state == 3'h1;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  assign io_mem_rready_0 = state == 3'h2;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _io_mem_awvalid_T_3 = state == 3'h3;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22, :30:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  assign io_mem_bready_0 = state == 3'h4;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22, :30:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        io_mem_arvalid_0 =
    _io_mem_awvalid_T & io_in_bits_decode_flags_1 & io_in_valid | _io_mem_arvalid_T_3;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:40:{50,60,76}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire [2:0]  io_mem_arsize_0 = {1'h0, io_in_bits_decode_funct3[1:0]};	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :20:30, :42:23]
  wire        io_mem_awvalid_0 =
    _io_mem_awvalid_T & io_in_bits_decode_flags_2 & io_in_valid | _io_mem_awvalid_T_3;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:44:{50,61,77}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _io_mem_wstrb_T_4 = io_in_bits_decode_funct3[1:0] == 2'h0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:20:30, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _io_mem_wstrb_T_5 = io_in_bits_decode_funct3[1:0] == 2'h1;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:20:30, :29:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _io_mem_wstrb_T_6 = io_in_bits_decode_funct3[1:0] == 2'h2;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:20:30, :29:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  reg  [7:0]  casez_tmp;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
  always_comb begin	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
    casez (io_in_bits_wb_res[1:0])	// @[/home/yzh/projectn/npc/src/main/LSU.scala:53:31, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
      2'b00:
        casez_tmp = io_mem_rdata[7:0];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:59:46, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
      2'b01:
        casez_tmp = io_mem_rdata[15:8];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:59:46, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
      2'b10:
        casez_tmp = io_mem_rdata[23:16];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:59:46, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
      default:
        casez_tmp = io_mem_rdata[31:24];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:59:46, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
    endcase	// @[/home/yzh/projectn/npc/src/main/LSU.scala:53:31, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
  end // always_comb
  wire [15:0] _GEN =
    io_in_bits_wb_res[1] ? io_mem_rdata[31:16] : io_mem_rdata[15:0];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:54:24, :60:46, /home/yzh/projectn/npc/src/main/utils/Utils.scala:28:47]
  wire [1:0]  waitARreadyNextState = io_mem_arready & io_mem_arvalid_0 ? 2'h2 : 2'h1;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:29:33, :40:76, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  wire [2:0]  waitAWreadyNextState = io_mem_awready & io_mem_awvalid_0 ? 3'h4 : 3'h3;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:30:33, :44:77, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  wire [2:0]  _state_T_14 =
    _io_mem_awvalid_T
      ? (io_in_bits_decode_flags_1 & io_in_valid
           ? {1'h0, waitARreadyNextState}
           : io_in_bits_decode_flags_2 & io_in_valid ? waitAWreadyNextState : 3'h0)
      : 3'h0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :28:22, :29:33, :30:33, :32:{33,41}, :33:{35,44}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  always @(posedge clock) begin	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
    if (reset)	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      state <= 3'h0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:28:22]
    else	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      state <=
        {_state_T_14[2],
         _state_T_14[1:0] | (_io_mem_arvalid_T_3 ? waitARreadyNextState : 2'h0)
           | (io_mem_rready_0 ? {~_memFinish_T, 1'h0} : 2'h0)}
        | (_io_mem_awvalid_T_3 ? waitAWreadyNextState : 3'h0)
        | (io_mem_bready_0 ? {~_memFinish_T_1, 2'h0} : 3'h0);	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :28:22, :29:33, :30:33, :35:33, :37:33, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
    initial begin	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
        state = _RANDOM[/*Zero width*/ 1'b0][2:0];	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :28:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid =
    io_in_valid & ~(io_in_bits_decode_flags_1 | io_in_bits_decode_flags_2) | _memFinish_T
    | _memFinish_T_1;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :21:28, :77:33, :79:{32,35,49}, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  assign io_out_bits_wb_res =
    io_in_bits_decode_flags_1
      ? (io_in_bits_decode_funct3 == 3'h0 ? {{24{casez_tmp[7]}}, casez_tmp} : 32'h0)
        | (io_in_bits_decode_funct3 == 3'h1 ? {{16{_GEN[15]}}, _GEN} : 32'h0)
        | (io_in_bits_decode_funct3 == 3'h2 ? io_mem_rdata : 32'h0)
        | (io_in_bits_decode_funct3 == 3'h4 ? {24'h0, casez_tmp} : 32'h0)
        | (io_in_bits_decode_funct3 == 3'h5 ? {16'h0, _GEN} : 32'h0)
      : io_in_bits_wb_res;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :28:22, :30:33, :70:20, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80, :23:{34,49}, :28:47]
  assign io_out_bits_wb_wen = io_in_bits_wb_wen;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  assign io_out_bits_wb_rd = io_in_bits_wb_rd;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  assign io_mem_awvalid = io_mem_awvalid_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :44:77]
  assign io_mem_awaddr = io_in_bits_wb_res;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  assign io_mem_awsize = io_mem_arsize_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :42:23]
  assign io_mem_wdata =
    (_io_mem_wstrb_T_4 ? {4{io_in_bits_wdata[7:0]}} : 32'h0)
    | (_io_mem_wstrb_T_5 ? {2{io_in_bits_wdata[15:0]}} : 32'h0)
    | (_io_mem_wstrb_T_6 ? io_in_bits_wdata : 32'h0);	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :48:{20,32}, :49:{20,32}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  assign io_mem_wstrb =
    (_io_mem_wstrb_T_4 ? 4'h1 << io_in_bits_wb_res[1:0] : 4'h0)
    | (_io_mem_wstrb_T_5 ? (io_in_bits_wb_res[1] ? 4'hC : 4'h3) : 4'h0)
    | {4{_io_mem_wstrb_T_6}};	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :53:{24,31}, :54:{19,24}, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  assign io_mem_bready = io_mem_bready_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  assign io_mem_arvalid = io_mem_arvalid_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :40:76]
  assign io_mem_araddr = io_in_bits_wb_res;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  assign io_mem_arsize = io_mem_arsize_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, :42:23]
  assign io_mem_rready = io_mem_rready_0;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  assign io_redirect_valid = io_in_bits_redirect_valid;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
  assign io_redirect_dnpc = io_in_bits_redirect_dnpc;	// @[/home/yzh/projectn/npc/src/main/LSU.scala:6:7]
endmodule

