// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MCU_EXU(	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  input         clock,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
                reset,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
                io_in_valid,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  input  [31:0] io_in_bits_src1,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_src2,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_src3,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  input         io_in_bits_wen,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  input  [3:0]  io_in_bits_rd,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  input  [2:0]  io_in_bits_decode_funct3,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  input         io_in_bits_decode_flags_0,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_1,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_2,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_3,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_4,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_5,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_in_bits_decode_flags_6,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output        io_out_valid,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_wb_res,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output        io_out_bits_wb_wen,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output [3:0]  io_out_bits_wb_rd,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_wdata,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output        io_out_bits_redirect_valid,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output [31:0] io_out_bits_redirect_dnpc,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output [2:0]  io_out_bits_decode_funct3,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
  output        io_out_bits_decode_flags_1,	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
                io_out_bits_decode_flags_2	// @[/home/yzh/projectn/npc/src/main/EXU.scala:7:14]
);

  wire [31:0] _GEN = {27'h0, io_in_bits_src2[4:0]};	// @[/home/yzh/projectn/npc/src/main/EXU.scala:20:25, :21:53]
  wire [62:0] _alu_T = {31'h0, io_in_bits_src1} << io_in_bits_src2[4:0];	// @[/home/yzh/projectn/npc/src/main/EXU.scala:20:25, :24:26]
  wire        _branchTaken_T_8 = io_in_bits_src1 < io_in_bits_src2;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:26:26]
  wire        _branchTaken_T_11 = io_in_bits_decode_funct3 == 3'h1;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _branchTaken_T_12 = io_in_bits_decode_funct3 == 3'h4;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _branchTaken_T_13 = io_in_bits_decode_funct3 == 3'h5;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _branchTaken_T_14 = io_in_bits_decode_funct3 == 3'h6;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire        _branchTaken_T_15 = &io_in_bits_decode_funct3;	// @[/home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92]
  wire [31:0] _alu_T_15 = _branchTaken_T_11 ? _alu_T[31:0] : 32'h0;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:24:26, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  wire [31:0] _res_T =
    io_in_bits_decode_flags_5
      ? {_alu_T_15[31:1],
         _alu_T_15[0] | io_in_bits_decode_funct3 == 3'h2
           & $signed(io_in_bits_src1) < $signed(io_in_bits_src2)
           | io_in_bits_decode_funct3 == 3'h3 & _branchTaken_T_8}
        | (_branchTaken_T_12 ? io_in_bits_src1 ^ io_in_bits_src2 : 32'h0)
        | (_branchTaken_T_13
             ? (io_in_bits_decode_flags_6
                  ? $signed($signed(io_in_bits_src1) >>> _GEN)
                  : io_in_bits_src1 >> _GEN)
             : 32'h0) | (_branchTaken_T_14 ? io_in_bits_src1 | io_in_bits_src2 : 32'h0)
        | (_branchTaken_T_15 ? io_in_bits_src1 & io_in_bits_src2 : 32'h0)
      : io_in_bits_decode_flags_4 | io_in_bits_decode_flags_6
          ? io_in_bits_src1 - io_in_bits_src2
          : io_in_bits_src1 + io_in_bits_src2;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:19:{16,26,47,66}, :21:{26,53,82}, :25:33, :26:26, :27:26, :29:26, :30:26, :32:16, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  reg  [63:0] io_out_bits_wb_res_mcycle64;	// @[/home/yzh/projectn/npc/src/main/CSR.scala:29:24]
  always @(posedge clock) begin	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
    if (reset)	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      io_out_bits_wb_res_mcycle64 <= 64'h0;	// @[/home/yzh/projectn/npc/src/main/CSR.scala:29:24]
    else	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      io_out_bits_wb_res_mcycle64 <= io_out_bits_wb_res_mcycle64 + 64'h1;	// @[/home/yzh/projectn/npc/src/main/CSR.scala:29:24, :30:18]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      `FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
    initial begin	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
        `INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
        end	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
        io_out_bits_wb_res_mcycle64 = {_RANDOM[2'h2], _RANDOM[2'h3]};	// @[/home/yzh/projectn/npc/src/main/CSR.scala:29:24, /home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
      `FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_out_valid = io_in_valid;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_wb_res =
    (io_in_bits_decode_flags_3
       ? (io_in_bits_src2[11:0] == 12'hB00 ? io_out_bits_wb_res_mcycle64[31:0] : 32'h0)
         | (io_in_bits_src2[11:0] == 12'hB80 ? io_out_bits_wb_res_mcycle64[63:32] : 32'h0)
         | (io_in_bits_src2[11:0] == 12'hF11 ? 32'h79737978 : 32'h0)
         | (io_in_bits_src2[11:0] == 12'hF12 ? 32'h12211D6 : 32'h0)
       : 32'h0) | (io_in_bits_decode_flags_0 ? {io_in_bits_src3[31:2], 2'h0} : 32'h0)
    | (io_in_bits_decode_flags_3 | io_in_bits_decode_flags_0 ? 32'h0 : _res_T);	// @[/home/yzh/projectn/npc/src/main/CSR.scala:26:28, :27:26, :29:24, :38:27, :39:27, /home/yzh/projectn/npc/src/main/EXU.scala:6:7, :32:16, :35:32, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80, :11:10, :16:{25,40}]
  assign io_out_bits_wb_wen = io_in_bits_wen;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_wb_rd = io_in_bits_rd;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_wdata = io_in_bits_src3;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_redirect_valid =
    io_in_bits_decode_flags_0 | io_in_bits_decode_flags_4
    & (io_in_bits_decode_funct3 == 3'h0 & io_in_bits_src1 == io_in_bits_src2
       | _branchTaken_T_11 & io_in_bits_src1 != io_in_bits_src2 | _branchTaken_T_12
       & $signed(io_in_bits_src1) < $signed(io_in_bits_src2) | _branchTaken_T_13
       & $signed(io_in_bits_src1) >= $signed(io_in_bits_src2) | _branchTaken_T_14
       & _branchTaken_T_8 | _branchTaken_T_15 & io_in_bits_src1 >= io_in_bits_src2);	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7, :26:26, :43:30, :44:26, :45:26, :46:33, :47:33, :49:26, :51:32, /home/yzh/projectn/npc/src/main/utils/Utils.scala:6:92, :7:80]
  assign io_out_bits_redirect_dnpc =
    {io_in_bits_decode_flags_4 ? io_in_bits_src3[31:2] : _res_T[31:2], 2'h0};	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7, :7:14, :32:16, :52:32, /home/yzh/projectn/npc/src/main/utils/Utils.scala:16:40]
  assign io_out_bits_decode_funct3 = io_in_bits_decode_funct3;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_decode_flags_1 = io_in_bits_decode_flags_1;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
  assign io_out_bits_decode_flags_2 = io_in_bits_decode_flags_2;	// @[/home/yzh/projectn/npc/src/main/EXU.scala:6:7]
endmodule

