// Generated by CIRCT firtool-1.155.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module MCU_AXI4LiteCrossbarNto1(	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
  input         clock,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
                reset,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
  output        io_in_0_awready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_0_awvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [31:0] io_in_0_awaddr,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [2:0]  io_in_0_awsize,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [31:0] io_in_0_wdata,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [3:0]  io_in_0_wstrb,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_0_bready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_in_0_bvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
                io_in_0_arready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_0_arvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [31:0] io_in_0_araddr,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [2:0]  io_in_0_arsize,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_0_rready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_in_0_rvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [31:0] io_in_0_rdata,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_in_1_arready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_1_arvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [31:0] io_in_1_araddr,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_in_1_rready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_in_1_rvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [31:0] io_in_1_rdata,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_out_awready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_out_awvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [31:0] io_out_awaddr,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [2:0]  io_out_awsize,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_out_wvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [31:0] io_out_wdata,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [3:0]  io_out_wstrb,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_out_bready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_out_bvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
                io_out_arready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_out_arvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [31:0] io_out_araddr,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output [2:0]  io_out_arsize,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  output        io_out_rready,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input         io_out_rvalid,	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
  input  [31:0] io_out_rdata	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14]
);

  wire _inputArbWrite_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29]
  wire _inputArbWrite_io_chosen;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29]
  wire _inputArbRead_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28]
  wire _inputArbRead_io_chosen;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28]
  reg  stateRead;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26]
  reg  chosenRead;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:138:29]
  wire inputArbRead_io_out_ready = io_out_arready & ~stateRead;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26, :138:70, :142:37]
  wire io_out_rready_0 = chosenRead ? io_in_1_rready : io_in_0_rready;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:138:29, :147:18]
  reg  stateWrite;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27]
  reg  chosenWrite;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:160:30]
  wire io_out_wvalid_0 = _inputArbWrite_io_out_valid & ~stateWrite;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29, :154:27, :160:73, :163:38]
  wire inputArbWrite_io_out_ready = io_out_awready & ~stateWrite;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27, :160:73, :164:38]
  wire io_out_bready_0 = ~chosenWrite & io_in_0_bready;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:160:30, :173:18]
  wire _chosenRead_T_1 = inputArbRead_io_out_ready & _inputArbRead_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28, :142:37, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  wire _chosenWrite_T_1 = inputArbWrite_io_out_ready & _inputArbWrite_io_out_valid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29, :164:38, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
  always @(posedge clock) begin	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    if (reset) begin	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      stateRead <= 1'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :132:26]
      chosenRead <= 1'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :138:29]
      stateWrite <= 1'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :154:27]
      chosenWrite <= 1'h0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :160:30]
    end
    else begin	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      if (stateRead)	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26]
        stateRead <= ~(io_out_rready_0 & io_out_rvalid);	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26, :135:26, :147:18, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
      else	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26]
        stateRead <= _chosenRead_T_1;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:132:26, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
      if (_chosenRead_T_1)	// @[src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
        chosenRead <= _inputArbRead_io_chosen;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28, :138:29]
      if (stateWrite)	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27]
        stateWrite <= ~(io_out_bready_0 & io_out_bvalid);	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27, :157:26, :173:18, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
      else	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27]
        stateWrite <= _chosenWrite_T_1;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:154:27, src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
      if (_chosenWrite_T_1)	// @[src/main/scala/chisel3/util/ReadyValidIO.scala:48:35]
        chosenWrite <= _inputArbWrite_io_chosen;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29, :160:30]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      `FIRRTL_BEFORE_INITIAL	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    initial begin	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
        `INIT_RANDOM_PROLOG_	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
        stateRead = _RANDOM[/*Zero width*/ 1'b0][0];	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :132:26]
        chosenRead = _RANDOM[/*Zero width*/ 1'b0][1];	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :132:26, :138:29]
        stateWrite = _RANDOM[/*Zero width*/ 1'b0][2];	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :132:26, :154:27]
        chosenWrite = _RANDOM[/*Zero width*/ 1'b0][3];	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :132:26, :160:30]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
      `FIRRTL_AFTER_INITIAL	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  MCU_Arbiter2_AXI4LiteBundleA inputArbRead (	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28]
    .io_in_0_ready     (io_in_0_arready),
    .io_in_0_valid     (io_in_0_arvalid),
    .io_in_0_bits_addr (io_in_0_araddr),
    .io_in_0_bits_size (io_in_0_arsize),
    .io_in_1_ready     (io_in_1_arready),
    .io_in_1_valid     (io_in_1_arvalid),
    .io_in_1_bits_addr (io_in_1_araddr),
    .io_out_ready      (inputArbRead_io_out_ready),	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:142:37]
    .io_out_valid      (_inputArbRead_io_out_valid),
    .io_out_bits_addr  (io_out_araddr),
    .io_out_bits_size  (io_out_arsize),
    .io_chosen         (_inputArbRead_io_chosen)
  );	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:128:28]
  MCU_Arbiter2_AXI4LiteBundleA inputArbWrite (	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29]
    .io_in_0_ready     (io_in_0_awready),
    .io_in_0_valid     (io_in_0_awvalid),
    .io_in_0_bits_addr (io_in_0_awaddr),
    .io_in_0_bits_size (io_in_0_awsize),
    .io_in_1_ready     (/* unused */),
    .io_in_1_valid     (1'h0),	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
    .io_in_1_bits_addr (32'h0),	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:120:14, :150:29]
    .io_out_ready      (inputArbWrite_io_out_ready),	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:164:38]
    .io_out_valid      (_inputArbWrite_io_out_valid),
    .io_out_bits_addr  (io_out_awaddr),
    .io_out_bits_size  (io_out_awsize),
    .io_chosen         (_inputArbWrite_io_chosen)
  );	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:150:29]
  assign io_in_0_bvalid = ~chosenWrite & io_out_bvalid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :160:30, :171:23, :172:30]
  assign io_in_0_rvalid = ~chosenRead & io_out_rvalid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :138:29, :145:23, :146:29]
  assign io_in_0_rdata = io_out_rdata;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
  assign io_in_1_rvalid = chosenRead & io_out_rvalid;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :138:29, :145:23, :146:29]
  assign io_in_1_rdata = io_out_rdata;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7]
  assign io_out_awvalid = io_out_wvalid_0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :163:38]
  assign io_out_wvalid = io_out_wvalid_0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :163:38]
  assign io_out_wdata = _inputArbWrite_io_chosen ? 32'h0 : io_in_0_wdata;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :120:14, :150:29, :165:17]
  assign io_out_wstrb = _inputArbWrite_io_chosen ? 4'h0 : io_in_0_wstrb;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :120:14, :150:29, :165:17]
  assign io_out_bready = io_out_bready_0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :173:18]
  assign io_out_arvalid = _inputArbRead_io_out_valid & ~stateRead;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :128:28, :132:26, :138:70, :141:37]
  assign io_out_rready = io_out_rready_0;	// @[/home/yzh/projectn/npc/src/main/AXI4.scala:119:7, :147:18]
endmodule

