// Generated by CIRCT firtool-1.155.0
module MCU_Arbiter2_AXI4LiteBundleA(	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7]
  output        io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input         io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input  [31:0] io_in_0_bits_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input  [2:0]  io_in_0_bits_size,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  output        io_in_1_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input         io_in_1_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input  [31:0] io_in_1_bits_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  input         io_out_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  output        io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  output [31:0] io_out_bits_addr,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  output [2:0]  io_out_bits_size,	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
  output        io_chosen	// @[src/main/scala/chisel3/util/Arbiter.scala:156:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7]
  assign io_in_1_ready = ~io_in_0_valid & io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:45:78, :149:7, :169:19]
  assign io_out_valid = io_in_0_valid | io_in_1_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7, :170:31]
  assign io_out_bits_addr = io_in_0_valid ? io_in_0_bits_addr : io_in_1_bits_addr;	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7, :159:15, :161:26, :163:19]
  assign io_out_bits_size = io_in_0_valid ? io_in_0_bits_size : 3'h0;	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7, :156:14, :159:15, :161:26, :163:19]
  assign io_chosen = ~io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:149:7, :158:13, :161:26, :162:17]
endmodule

